---
title: "Third Post"
author: "Group 2"
editor: visual
description: "This post details our drafting of data.qmd and initial analysis"
date: "2024-10-25"
---

During the third week, we started drafting our data.qmd page for the final project. We described where we found our dataset and why the data was collected. We also described all the variables in our dataset. 

The dataset we used can be found at <https://www.kaggle.com/datasets/mustafaadelibrahim/traffic-stops-in-rhode-islandpolicing-activities?resource=download>. The dataset on traffic stops in Rhode Island is part of a larger collection by the Stanford Open Policing Project. This project aims to collect and standardize data on vehicle and pedestrian stops across 31 U.S. states, gathering over 200 million records to promote transparency and accountability in policing. The data was curated by a team of researchers and journalists at Stanford University, blending statistical analysis with data journalism.

The dataset had 15 variables: state, stop_date, stop_time, county_name, driver_gender, driver_race, violation_description, violation, search_conducted, search_type, stop_outcome, is_arrested, stop_duration, drugs_related_stop, and district. This data set only focused on Rhode Island so the state was irrelevant. Stop_date and stop_time stated the date and time of day that the traffic stop occurred. The county_name was an empty column. Driver_gender and driver_race detailed the gender and race of the driver who was stopped. The variable violation gave a general classification for the violation while violation_description gave a more detailed description of the reason for the traffic stop. Search_conducted (boolean), search_type, stop_outcome, is_arrested (boolean), stop_duration, drugs_related_stop (boolean) gave more details as to what occurred during the traffic stop which gives us a better idea for the severity of the traffic violation. 

In the `”data.qmd”` file, we included at the bottom some initial analysis and visualization of the distribution of traffic stops by race. You can find a bar plot and table summary showing how many stops are in the data set across each particular race. Although it may be skewed by the population proportions for each race, we can see that whites are stopped most frequently, then blacks, then hispanics, then asians. 
