---
title: "First Post"
author: "Group 2"
format: html
editor: visual
---

Data set 1:

Link to dataset: <https://www.kaggle.com/datasets/mustafaadelibrahim/traffic-stops-in-rhode-islandpolicing-activities?resource=download>

The dataset of traffic stops by police officers was collected by the Stanford Open Policing Project. It has 15 columns and 91741 rows. Through using this data, we hope to investigate if the driver's race is correlated with the amount and severity of the stop. Therefore in terms of data cleaning, we might focus on the variables driver_race, search_conducted, stop_outcome, stop_duration, and is_arrested.

Data set 2

Link to data set: <https://catalog.data.gov/dataset/alzheimers-disease-and-healthy-aging-data/resource/b2443e45-68aa-4004-b97a-e62c4c28502f>

The Alzheimer's data set includes 284142 rows by 31 columns. The data set reports the number of people of certain age groups and races that were observed to have Alzheimer’s within a specified period of time, and records other information such as health condition and medical history. With this data set, we can study a potential racial disparity in the number of people that suffer from Alzheimer’s. The data set is sourced from the Department of Health and Human Services, and was published by the Center for Disease Control and Prevention. The data was collected over the period of 2015 to 2022. The data can be easily loaded as it is stored simply in a CSV file. Some cleaning may be necessary as there are many variables that may be extraneous to our study, such as geographic location. In addition, there are many rows where some data entries are missing, and they will have to be cleaned out.
