{
  "hash": "20574586375688b06356b88f089b6d4a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sixth Post\"\nauthor: \"Group 2\"\nformat: html\neditor: visual\ndescription: \"This post details our EDA of San Fransicso data\"\ndate: \"2024-11-18\"\n---\n\n\nThis week we finished implementing the data from San Francisco into our data set. In addition, we performed preliminary EDA on the San Francisco data by implementing the visualization and modeling methods used earlier. The complete data set with both the SF and RI data is generated through `\"load_and_clean_data2.R\"`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"scripts/load_and_clean_data2.R\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\nJoining with `by = join_by(stop_date, stop_time, driver_gender, driver_race, violation, search_conducted, search_type, stop_outcome, is_arrested, stop_duration, drugs_related_stop, district, state)`\n```\n\n\n:::\n\n```{.r .cell-code}\nfull_traffic_data_clean|>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 13\n   stop_date  stop_time driver_gender driver_race violation search_conducted\n   <date>     <chr>     <chr>         <chr>       <chr>     <lgl>           \n 1 2005-01-04 12:55:00  M             white       Equipment FALSE           \n 2 2005-01-23 23:15:00  M             white       Speeding  FALSE           \n 3 2005-02-17 04:15:00  M             white       Speeding  FALSE           \n 4 2005-02-20 17:15:00  M             white       Other     FALSE           \n 5 2005-02-24 01:20:00  F             white       Speeding  FALSE           \n 6 2005-03-14 10:00:00  F             white       Speeding  FALSE           \n 7 2005-03-29 21:55:00  M             white       Speeding  FALSE           \n 8 2005-04-04 21:25:00  M             white       Speeding  FALSE           \n 9 2005-07-14 11:20:00  F             white       Speeding  FALSE           \n10 2005-07-14 19:55:00  M             white       Speeding  FALSE           \n# ℹ 7 more variables: search_type <chr>, stop_outcome <chr>, is_arrested <lgl>,\n#   stop_duration <chr>, drugs_related_stop <lgl>, district <chr>, state <chr>\n```\n\n\n:::\n:::\n\n\nBelow, you can see our code for modeling the likelihood of arrest by certain factors for our SF data alone. We can observe a noticeable difference in this model’s performance compared to the RI model; Race does not play as significant a role in predicting the probability of arrest here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(is_arrested ~ driver_race + driver_gender + stop_date + district,\n             data = sf_traffic_data_clean, \n             family = binomial)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = is_arrested ~ driver_race + driver_gender + stop_date + \n    district, family = binomial, data = sf_traffic_data_clean)\n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -8.692e-01  1.624e-01  -5.351 8.73e-08 ***\ndriver_raceblack     1.078e+00  3.541e-02  30.432  < 2e-16 ***\ndriver_racehispanic  8.353e-01  3.741e-02  22.329  < 2e-16 ***\ndriver_raceother     1.176e-01  4.504e-02   2.610 0.009058 ** \ndriver_racewhite     2.818e-01  3.383e-02   8.330  < 2e-16 ***\ndriver_genderM       4.391e-01  2.314e-02  18.979  < 2e-16 ***\nstop_date           -3.027e-04  1.026e-05 -29.496  < 2e-16 ***\ndistrictB            7.260e-02  4.985e-02   1.456 0.145320    \ndistrictC            1.405e-01  4.904e-02   2.865 0.004167 ** \ndistrictD            6.713e-01  4.678e-02  14.352  < 2e-16 ***\ndistrictE            2.036e-01  5.176e-02   3.933 8.38e-05 ***\ndistrictF            9.373e-02  5.664e-02   1.655 0.097986 .  \ndistrictG            3.370e-01  5.168e-02   6.521 6.99e-11 ***\ndistrictH            3.756e-01  4.690e-02   8.009 1.15e-15 ***\ndistrictI            1.855e-01  5.032e-02   3.687 0.000227 ***\ndistrictJ            3.987e-01  5.448e-02   7.317 2.53e-13 ***\ndistrictK           -8.336e-01  5.027e-01  -1.658 0.097306 .  \ndistrictS            3.346e-01  4.520e-01   0.740 0.459149    \ndistrictT            9.274e-01  5.083e-01   1.824 0.068095 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 121691  on 852882  degrees of freedom\nResidual deviance: 117985  on 852864  degrees of freedom\n  (52187 observations deleted due to missingness)\nAIC: 118023\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        (Intercept)    driver_raceblack driver_racehispanic    driver_raceother \n          0.4192828           2.9380292           2.3054834           1.1247418 \n   driver_racewhite      driver_genderM           stop_date           districtB \n          1.3254798           1.5512986           0.9996973           1.0753016 \n          districtC           districtD           districtE           districtF \n          1.1508465           1.9568498           1.2257600           1.0982603 \n          districtG           districtH           districtI           districtJ \n          1.4007383           1.4558570           1.2038369           1.4898221 \n          districtK           districtS           districtT \n          0.4345004           1.3973248           2.5279065 \n```\n\n\n:::\n:::\n\n\n**Findings:**\n\n1.  Intercept: The negative coefficient for the intercept (-8.692e-01) indicates that when all predictors are at their baseline (e.g., driver race as a reference category, stop date at zero, and driver gender as female), the log-odds of an arrest are negative, suggesting a lower baseline probability of arrest.\n\n2.  Driver Race: \n\nBlack Drivers: The coefficient (1.078e+00, p \\< 0.001) shows a significant positive association between being a Black driver and the likelihood of arrest, indicating a higher likelihood compared to the baseline race category.\n\nHispanic Drivers: The coefficient (8.353e-01, p \\< 0.001) also shows a significant positive association, suggesting that Hispanic drivers are more likely to be arrested than the baseline race category. \n\nWhite Drivers: The coefficient (2.818e-01, p \\< 0.001) suggests a smaller, but still significant, positive association with the likelihood of arrest. \n\nOther Race: The coefficient (1.176e-01, p = 0.009058) suggests a modest but significant positive relationship with arrest likelihood.\n\n3.  Driver_gender: The positive coefficient (4.391e-01, p \\< 0.001) indicates that male drivers are significantly more likely to be arrested than female drivers.\\\n\n4.  Stop_dates: The small negative coefficient (-3.027e-04, p \\< 0.001) suggests that the likelihood of arrest slightly decreases over time, a statistically significant trend.\\\n\n5.  Districts: Districts C, D, G, H, and J have significant positive coefficients, suggesting these zones are associated with a higher likelihood of arrest. Districts B, S, and T do not show a statistically significant effect on the arrest likelihood, as indicated by their higher p-values. District K shows a negative coefficient, but it is not statistically significant, indicating no strong evidence of reduced arrest likelihood.\n\n**Statistical Significance:**\n\nThe model's p-values show that most predictors, including race (Black, Hispanic, White), gender, stop date, and certain districts (C, D, G, H, J), are statistically significant (p \\< 0.05), indicating they have significant relationships with the likelihood of arrest. However, predictors such as districts B, S, T, and K are not statistically significant, suggesting no strong evidence of their association with the response variable.\\\n\n**Model Performance:**\n\n-   Model Performance: AIC (118023): The Akaike Information Criterion indicates the model's fit, with a lower value suggesting a better fit. \n\n-   Null Deviance: 121691 Residual Deviance: 117985 The reduction in deviance demonstrates that the model explains more variance in the response variable compared to an intercept-only model.\n\n**Interpretation:**\n\nThis analysis suggests that race and gender remain significant predictors of arrest during traffic stops. Specifically: Black and Hispanic drivers are significantly more likely to be arrested. Male drivers have a higher likelihood of arrest compared to female drivers. The model also reveals district-level differences, with certain districts such as Districts D, G, and H having a stronger association with arrests, while others show a weaker or no significant association. Stop date trends suggest a slight decrease in arrest likelihood over time.\n\nBelow are some graphs to visualize the raw San Francisco data. As seen below, this data includes a much larger proportion of black and hispanic drivers compared to the RI data, and Blacks seem to be given warnings with a slightly higher proportion than other races:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrest_rates <- sf_traffic_data_clean %>%\n  group_by(driver_race) %>%\n  summarize(arrest_rate = mean(is_arrested, na.rm = TRUE)) \n\nggplot(arrest_rates, aes(x = factor(driver_race), y = arrest_rate, fill = factor(driver_race))) +\n  geom_bar(stat = \"identity\") +\n  labs(title = \"Arrest Rate by Race\", x = \"Race\", y = \"Arrest Rate\") +\n  scale_y_continuous(labels = scales::percent) +    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](sixthpost_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nrace_stop_counts <- sf_traffic_data %>%\n  count(subject_race, raw_result_of_contact_description)\n\nggplot(race_stop_counts, aes(x = factor(subject_race), y = n, fill = raw_result_of_contact_description)) +\n  geom_bar(stat = \"identity\", position = \"fill\") + \n  labs(title = \"Distribution of Stop Results by Race\", x = \"Race\", y = \"Proportion\") +\n  scale_y_continuous(labels = scales::percent) + theme_minimal()\n```\n\n::: {.cell-output-display}\n![](sixthpost_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n",
    "supporting": [
      "sixthpost_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}